### ISSUE TITLE
Help with implementing the Reactive Scrabble benchmark

### ISSUE THREAD

**Issue by akarnokd** [reactors-io/reactors#63]
I'd like to implement the Reactive Scrabble benchmark with Reactors.IO but I have difficulties finding and applying the necessary operators (I'm not a Scala developer by the way). [This is how far I've gotten](https://github.com/akarnokd/akarnokd-misc-scala/blob/master/src/main/scala/ScrabbleWithReactorsIO.scala#L196). Any help would be appreciated.

### 1) chars: Streaming the characters of a String on-demand

In other libraries, one would create a range with the length of the string and map each index into a character. A twitter reply mentioned `.toEvents` which I'm not sure how to apply as this doesn't work on its own (missing import?).

```scala
(string: String) =>(0 until string.length).toEvents().map((i) => string.charAt(i))
```

### 2) flatMap: flatmapping an iterable sequence

I need to generate `Events[Map.Entry[Int, Long]]` from `Events[Map[Int, Long]]` by calling `entrySet()` then flattening the returned `Set[Map.Entry[Int, Long]]`.

I found `union` that makes `Events[Events[T]]` into `Events[T]` but then I need a way to turn `Set[T]` into `Events[T]` in some way (unbatch?).

### 3) fromIterable: Turning an `Iterable`/`Seq` sequence into `Events`

Is there a way to turn into an `Events` that only sends out the elements if there is demand for it?

**Comment by axel22** [comment]
1. This should work if you import the `io.reactors.protocol` package:

```
import io.reactors.protocol._
(s: String) => (0 until s.length).toEvents.map(i => string.charAt(i))
```

Note that event streams in Reactors are lazy. This means that in order to start emitting events, you need to invoke one of the `on*` methods, such as `onEvent`, or one of the `to*` methods, such as `toSignal`.

The event stream obtained from a collection (such as range) is, in addition, cold. This means that the events are not emitted until you subscribe to this event stream. In the case of `toEvents`, all events are immediately available (since the range contains them), so they will all be emitted right away, synchronously.

2. The `union` combinator (which has the more familiar alias `flatten`) combines all events from nested event streams. You want to map the event stream of maps into an event stream of entry sets, and then to an event stream of event streams with those entries, then everything.

```
time     ----------------------------->
in       ---M1------------M2---------->
            e1-e2-e3-|
                          f1-f2-f3-|
out      ---e1-e2-e3----f1-f2-f3 ----->
```

Here's one way you could achieve what you want (note that you need to create the Java set to a Scala set):

```
import io.reactors._
import io.reactors.protocol._
import scala.collection.convert.decorateAll._

val mapEvents: Events[Map[Int, Long]] = new Events.Emitter[Map[Int, Long]]
mapsEvents.map(m => m.entrySet.toEvents).union
```

This does the same:

```
mapsEvents.map(m => m.entrySet).map(s => s.toEvents).union
```

3. Hm, if by demand you mean that there is a subscriber for it, then that's already the case with event streams created from collections. Such an event stream will traverse the collection, and emit all the elements as events. In other words, when you call `toEvents` on a collection, nothing will be emitted until somebody calls `onEvent` on that event stream. All "cold" event streams behave like this.

Hot event streams (such as `system.clock.timeout`) emit events regardless of whether there are `onEvent` calls.

Generally, though, there is the `toCold` combinator which converts an event stream into a signal that only subscribes to its event stream if there is someone subscribed to that signal.

**Comment by akarnokd** [comment]
Thanks for the reply, the suggestions now compile but the app now fails with an NPE. I'll post a separate issue.
